# numpy小白教程

## 导入numpy

In [ ]:
import numpy 
#最常用
import numpy as np
from numpy import *
from numpy import cos

## 一维数组

### 一维数组的创建

#### 无指定类型创建

In [1]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.arange(10,20)
arr3 = np.random.randint(1,10,(3,))
print('普通方法创建:',arr1)
print('arange方法创建:',arr2)
print('random方法创建',arr3)

普通方法创建: [1 2 3]
arange方法创建: [10 11 12 13 14 15 16 17 18 19]
random方法创建 [6 2 7]


#### 指定类型创建

In [147]:
import numpy as np
#以下dtype的值均为默认值
#整型有int8、int16、int32、int64
#浮点型有float16、float32、float64
#复数型有complex64、complex128
arr1 = np.array([1,2,3], dtype='int32')
arr2 = np.array([1.5,2,3], dtype='float64')
arr3 = np.array([1,2+6j,3], dtype='complex')
print('32位整型数组:',arr1)
print('64位浮点型数组:',arr2)
print('128位复数型数组:',arr3)

32位整型数组: [1 2 3]
64位浮点型数组: [1.5 2.  3. ]
128位复数型数组: [1.+0.j 2.+6.j 3.+0.j]


### 一维数组的各种属性

In [38]:
import numpy as np
arr = np.array([1,2,3,4,5])
#数组的类型
print(type(arr))
#数组中元素数据类型
print(arr.dtype)
#数组的大小
print(arr.shape)
#数组的元素个数
print(arr.size)
#数组的维度
print(arr.ndim)
#数组中每个元素的字节大小，因为这里是int32，所以字节大小是32/8
print(arr.itemsize)

<class 'numpy.ndarray'>
int32
(5,)
5
1
4


### 数组元素类型的转换

In [99]:
import numpy as np
arr1 = np.array([1.5,2.8,3.3],dtype='float64')
arr1.astype('int32')
arr2 = np.array([1.5,2,8],dtype='float64')
arr2 = arr2.astype('int32')
print(arr1)
print(arr2)

[1.5 2.8 3.3]
[1 2 8]


## 多维数组

### 多维数组的创建

In [110]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.arange(15).reshape(3,5)
print(arr1)
print(arr1.ndim)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


### 特殊多维数组

In [141]:
import numpy as np
#两行两列全零数组
arr_zero = np.zeros((2,2))
#三行三列全一数组
arr_one =  np.ones((3,3))
#三行三列趋零数组
arr_empty = np.empty((3,3))
#三行三列对角矩阵，0代表无偏移，1代表向右偏移，每行左边补零，-1则相反。
arr_eye = np.eye(3,3,0)
#两行三列全5数组
arr_full = np.full((2,3),5)
print(arr_zero)
print('-----------------------------')
print(arr_one)
print('-----------------------------')
print(arr_empty)
print('-----------------------------')
print(arr_eye)
print('-----------------------------')
print(arr_full)

[[0. 0.]
 [0. 0.]]
-----------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
-----------------------------
[[5 5 5]
 [5 5 5]]


## 数组的运算

### 一维数组

#### 数组与数字的运算

In [3]:
import numpy as np
arr = np.arange(1,6)
print(arr+1)
print(arr*2)

[2 3 4 5 6]
[ 2  4  6  8 10]


In [8]:
#列表不可以进行此操作
# print([1,2,3]+1)

In [14]:
#数组求和
import numpy as np
arr = np.array([1,2,3])
print(arr.sum())
print(sum(arr))

6
6


#### 数组与数组的运算

In [7]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([4,5,6,7])
print(arr1+arr2)
print(arr1*arr2)
# 行元素的个数不相同，不可以相加或相乘
# print(arr1+arr3)
# print(arr1*arr3)

[5 7 9]
[ 4 10 18]


In [6]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[1,2,3],[4,5,6,7]])
print(arr1+arr2)
# 行元素的个数不相同，不可以相乘
# print(arr1+arr3)

[[2 4 6]
 [5 7 9]]


In [5]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3 = np.array([[1,2,3],[4,5,6,7]])
print(arr1*arr2)
# 行元素的个数不相同，不可以相乘
# print(arr1*arr3)

[[[ 1  4  9]
  [ 4 10 18]]

 [[ 1  4  9]
  [ 4 10 18]]]


### 二维数组

#### 数组与数字的运算

In [2]:

import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr+1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 数组与数组的运算

In [4]:
import numpy as np
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(2,6).reshape(2,2)
arr3 = np.arange(1,7).reshape(2,3)
print(arr1)
print('---------------')
print(arr2)
print('---------------')
#形状不同的两个数组不可以相加或相乘
# print(arr1*arr2)
# print(arr1*arr3)

[[0 1]
 [2 3]]
---------------
[[2 3]
 [4 5]]
---------------


## 数组的索引与切片

### 索引

#### 一维

In [2]:
#和列表中的索引一样
import numpy as np
arr = np.arange(10)
print(arr)
print(arr[6])
print(arr[-2])

[0 1 2 3 4 5 6 7 8 9]
6
8


#### 多维

##### 普通索引

In [3]:
import numpy as np
#二维
arr1 = np.arange(9).reshape(3,3)
#三维
arr2 = np.arange(8).reshape(2,2,2)
print(arr1)
print('------------')
print(arr1[1])
print(arr1[1,1])#相当于arr1[1][1]
print('------------')
print(arr2)
print('------------')
print(arr2[1,0,1])#相当于arr2[1][0][1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------
[3 4 5]
4
------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
------------
5


##### 布尔索引

In [103]:
import numpy as np
arr1 = np.array([1,4,1,5])
#等于1的位置为True，否则为False
print(arr1==1)
arr2 = np.array([1,2,3,4])
arr3 = np.array([[1,2,3,4],[5,7,9,6],[3,6,8,2],[4,9,3,1]])
'''因为[arr==1]的True在位置0、2，故取arr2
中的第0、2个数，二维则取第0、2行，依次类推,
arr2的元素个数或者行数(更高维度依次类推)必须
与arr1的元素个数相同
'''
print(arr2[arr1==1])
print(arr2[arr1>2])
#arr1==1或者arr1==4的行
print(arr2[(arr1==1)|(arr1==4)])
#取0、2行的第一个数
print(arr3[arr1==1,1])
#取0、2行的第一到第三个数
print(arr3[arr1==1,1:4])

[ True False  True False]
[1 3]
[2 4]
[1 2 3]
[2 6]
[[2 3 4]
 [6 8 2]]


##### 花式索引

In [86]:
import numpy as np
arr1 = np.array([2,4,3,9,6])
arr2 = np.array([[1,3,7],[5,8,9],[3,7,4],[7,6,8],[9,1,0],[2,0,5]])
#第一二四个
print(arr1[[1,2,4]])
print('-------------')
#第二三四行
print(arr2[[2,3,4]])
print('-------------')
#第二行第二个，第一行第零个，第四行第一个
print(arr2[[2,1,4],[2,0,1]])

[4 3 6]
-------------
[[3 7 4]
 [7 6 8]
 [9 1 0]]
-------------
[4 5 1]


### 切片

#### 一维

In [40]:
#基本和列表的切片一样
import numpy as np
arr = np.arange(10)
print(arr)
print('------------')
print('arr[:]的值为：',arr[:])
print('arr[1:]的值为：',arr[1:5])
#超过索引值不报错,结果和arr[2:]一致，这和列表有所不同
print(arr[2:100])
print('arr[1:5:2]的值为',arr[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
------------
arr[:]的值为： [0 1 2 3 4 5 6 7 8 9]
arr[1:]的值为： [1 2 3 4]
[2 3 4 5 6 7 8 9]
arr[1:5:2]的值为 [1 3]


#### 多维

In [4]:
import numpy as np
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(12).reshape(2,2,3)
print('arr1为:\n',arr1)
print('-----------------')
print('arr1[1:3]的值为：\n',arr1[1:3])
print('-----------------')
print('arr1[1:3:2]的值为：\n',arr1[1:3:2])
print('=================')
print('arr2为：\n',arr2)
print('-----------------')
print('arr2[1:]的值为：\n',arr2[1:])

arr1为:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------------
arr1[1:3]的值为：
 [[3 4 5]
 [6 7 8]]
-----------------
arr1[1:3:2]的值为：
 [[3 4 5]]
arr2为：
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
-----------------
arr2[1:]的值为：
 [[[ 6  7  8]
  [ 9 10 11]]]


In [73]:
import numpy as np
arr = np.arange(64).reshape(8,8)
print(arr)
print('-------------------------')
print('第一行的值为：(数组的维度为1)')
print(arr[0,:])
print('第一行的值为：(数组的维度为2)')
print(arr[:1,:])
print('第一列的值为：(数组的维度为1)')
print(arr[:,0])
print('第一列的值为：(数组的维度为2)')
print(arr[:,:1])
print('第一行的第一到第五个数为:',arr[0,1:6])#相当于arr[0][1:6]
print('-------------------------')
print('第一二行和第二三列组成的数组为:')
print(arr[1:3,2:4])
print('第一三行和第二四列交点组成的数组为：')
print(arr[1:4:2,2:5:2])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
-------------------------
第一行的值为：(数组的维度为1)
[0 1 2 3 4 5 6 7]
第一行的值为：(数组的维度为2)
[[0 1 2 3 4 5 6 7]]
第一列的值为：(数组的维度为1)
[ 0  8 16 24 32 40 48 56]
第一列的值为：(数组的维度为2)
[[ 0]
 [ 8]
 [16]
 [24]
 [32]
 [40]
 [48]
 [56]]
第一行的第一到第五个数为: [1 2 3 4 5]
-------------------------
第一二行和第二三列组成的数组为:
[[10 11]
 [18 19]]
第一三行和第二四列交点组成的数组为：
[[10 12]
 [26 28]]


### 更改数组的值

In [106]:
import numpy as np
arr1 = np.array([1,2,3])
#为了不改变arr1的数据，复制副本
arr1_1 = arr1.copy()
arr1_2 = arr1.copy()
arr1_1[2]=4
arr1_2[:2]=5
arr1[2]=8
print(arr1_1)
print(arr1_2)
#arr1的原始数据发生改变
print(arr1)

[1 2 4]
[5 5 3]
[1 2 8]


## 数组中基本的方法和属性

### 方法

In [79]:
import numpy as np
#9个大小在[1,10)的元素组成的3*3的数组，reshape为变形方法
arr1 = np.random.randint(1,10,9).reshape(3,3)
arr2 = np.arange(9,18).reshape(3,3)
print('------------水平组合--------------')
print(np.hstack((arr1, arr2)))
print('------------垂直组合--------------')
print(np.vstack((arr1, arr2)))
print('-------------深度组合-------------')
print(np.dstack((arr1, arr2)))


------------水平组合--------------
[[ 5  7  1  9 10 11]
 [ 1  7  4 12 13 14]
 [ 8  9  3 15 16 17]]
------------垂直组合--------------
[[ 5  7  1]
 [ 1  7  4]
 [ 8  9  3]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
-------------深度组合-------------
[[[ 5  9]
  [ 7 10]
  [ 1 11]]

 [[ 1 12]
  [ 7 13]
  [ 4 14]]

 [[ 8 15]
  [ 9 16]
  [ 3 17]]]


In [80]:
print('-------------按行排序-------------')
print(np.sort(arr1))
print('-------------按列排序-------------')
print(np.msort(arr1))
print('-------------排序后返回下标-------------')
print(np.argsort(arr1))

-------------按行排序-------------
[[1 5 7]
 [1 4 7]
 [3 8 9]]
-------------按列排序-------------
[[1 7 1]
 [5 7 3]
 [8 9 4]]
-------------排序后返回下标-------------
[[2 0 1]
 [0 2 1]
 [2 0 1]]


In [81]:
print('-------------平均值-------------')
print(np.mean(arr1))
print('-------------方差---------------')
print(np.var(arr1))
print('-------------标准差---------------')
print(np.std(arr1))

-------------平均值-------------
5.0
-------------方差---------------
7.777777777777778
-------------标准差---------------
2.788866755113585


In [82]:
print('-------------累乘(每一次的结果)---------------')
print(arr1.cumprod())
print('-------------累乘(最后结果)---------------')
print(arr1.prod())

-------------累乘(每一次的结果)---------------
[     5     35     35     35    245    980   7840  70560 211680]
-------------累乘(最后结果)---------------
211680


In [83]:
print('-------------返回数组所对应条件的行列组成的数组组成的元组---------------')
print(np.where(arr1==4))
print('-------------返回数组所对应条件的行列组成的数组---------------')
print(np.argwhere(arr1==4))
print('-------------返回arr2中满足条件的元素所对应的索引组成的数组，没有条件满足则返回空数组---------------')
print(np.extract([arr1==4],arr2))

-------------返回数组所对应条件的行列组成的数组组成的元组---------------
(array([1], dtype=int64), array([2], dtype=int64))
-------------返回数组所对应条件的行列组成的数组---------------
[[1 2]]
-------------返回arr2中满足条件的元素所对应的索引组成的数组，没有条件满足则返回空数组---------------
[14]


In [84]:
print('-------------点积---------------')
print(np.dot(arr1,arr2))#与arr1*arr2不同
print('-------------返回数组的正负(1或-1)---------------')
print(np.sign(arr1))
print('-------------修剪数组---------------')
print(arr1.clip(4,7))#将大于4的元素变为4，不小于7的元素变为7
print('-------------判断是否为实数---------------')
print(np.isreal(arr1))
print('-------------替换---------------')
print(np.piecewise(arr1,[arr1==4],[8]))#把4换为8，其它为0

-------------点积---------------
[[144 157 170]
 [153 165 177]
 [225 245 265]]
-------------返回数组的正负(1或-1)---------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]
-------------修剪数组---------------
[[5 7 4]
 [4 7 4]
 [7 7 4]]
-------------判断是否为实数---------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------替换---------------
[[0 0 0]
 [0 0 8]
 [0 0 0]]


In [85]:
#数组转列表
print(type(arr1))
arr1 = arr1.tolist()
print(type(arr1))

<class 'numpy.ndarray'>
<class 'list'>


### 属性

In [71]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 数组的大小
print(arr.shape)
#维度
print(arr.ndim)
#元素个数
print(arr.size)
#字节
print(arr.itemsize)
#转置
print(arr.T)
print('---------------------')
arr1.flat=5#数组中的元素被5覆盖,相当于arr1.fill(5)
print(arr1)

(3, 3)
2
9
4
[[1 4 7]
 [2 5 8]
 [3 6 9]]
---------------------
[[5 5 5]
 [5 5 5]
 [5 5 5]]


## 矩阵

### 矩阵的创建

In [12]:
import numpy as np
mat1 = np.mat([[1,2],[4,5]])
mat2 = np.matrix([[4,5],[7,8]])
print(type(mat1),type(mat2))

<class 'numpy.matrixlib.defmatrix.matrix'> <class 'numpy.matrixlib.defmatrix.matrix'>


In [35]:
#矩阵必须是二维的，与数组不同
import numpy as np
mat = np.mat([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(mat)

ValueError: matrix must be 2-dimensional

In [36]:
import numpy as np
mat = np.mat([1,2,3])
print(mat.ndim)

2


### 矩阵的方法和属性

In [46]:
import numpy as np
mat1 = np.mat([[1,2],[3,4]])
mat2 = np.mat([[5,6],[7,8]])
print('---------内积----------')
#第一个矩阵的列数必须与第二个矩阵的行数相等，与数组的乘积不同
print(mat1*mat2)
print('---------转置----------')
print(mat1.T)
#数组没有逆矩阵和共轭这一说法
print('---------逆矩阵--------')
print(mat1.I)
print('---------共轭----------')
print(mat1.H)

---------内积----------
[[19 22]
 [43 50]]
---------转置----------
[[1 3]
 [2 4]]
---------逆矩阵--------
[[-2.   1. ]
 [ 1.5 -0.5]]
---------共轭----------
[[1 3]
 [2 4]]
